#!/usr/bin/env python3
import csv
import gzip
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASICS_PATH = Path('/tmp/title.basics.tsv.gz')
RATINGS_PATH = Path('/tmp/title.ratings.tsv.gz')
OUTPUT_PATH = ROOT / 'src/data/movies.js'
TOP_LIMIT = 1000
MIN_VOTES = 25000


def read_ratings():
    ratings = {}
    rating_sum = 0.0
    rating_count = 0
    with gzip.open(RATINGS_PATH, 'rt', encoding='utf-8', newline='') as fh:
        reader = csv.DictReader(fh, delimiter='\t')
        for row in reader:
            votes = int(row['numVotes'])
            rating = float(row['averageRating'])
            ratings[row['tconst']] = (rating, votes)
            if votes >= MIN_VOTES:
                rating_sum += rating
                rating_count += 1
    mean_rating = rating_sum / rating_count
    return ratings, mean_rating


def clean(value):
    return '' if value == r'\N' else value


def read_movies(ratings, mean_rating):
    movies = []
    with gzip.open(BASICS_PATH, 'rt', encoding='utf-8', newline='') as fh:
        reader = csv.DictReader(fh, delimiter='\t')
        for row in reader:
            if row['titleType'] != 'movie' or row['isAdult'] != '0':
                continue
            rating_data = ratings.get(row['tconst'])
            if not rating_data:
                continue
            rating, votes = rating_data
            if votes < MIN_VOTES:
                continue

            year = clean(row['startYear'])
            genres = clean(row['genres'])
            title = clean(row['primaryTitle'])
            if not title or not year or not genres:
                continue

            weighted_rating = (votes / (votes + MIN_VOTES)) * rating + (MIN_VOTES / (votes + MIN_VOTES)) * mean_rating
            genre_text = genres.replace(',', ', ')
            vote_text = f"{votes:,}"
            description = f"A {year} {genre_text} film with an IMDb rating of {rating:.1f} based on {vote_text} votes."
            movies.append({
                'id': row['tconst'],
                'title': title,
                'year': int(year),
                'genres': genres.split(','),
                'rating': rating,
                'votes': votes,
                'weightedRating': round(weighted_rating, 4),
                'description': description,
            })
    movies.sort(key=lambda movie: (movie['weightedRating'], movie['votes']), reverse=True)
    return movies[:TOP_LIMIT]


def write_js(movies):
    lines = [
        '// Generated by scripts/build_imdb_movies.py from IMDb non-commercial datasets.',
        '// Source: https://developer.imdb.com/non-commercial-datasets/',
        f'// Filter: titleType=movie, isAdult=0, numVotes>={MIN_VOTES}; sorted by weighted IMDb rating.',
        f'export const MOVIES = {json.dumps(movies, ensure_ascii=False, indent=4)};',
        '',
        'export const MOVIE_TITLES = MOVIES.map(movie => movie.title);',
        'export const MOVIE_DESCRIPTIONS = MOVIES.map(movie => movie.description);',
        '',
    ]
    OUTPUT_PATH.write_text('\n'.join(lines), encoding='utf-8')


def main():
    if not BASICS_PATH.exists() or not RATINGS_PATH.exists():
        raise SystemExit('Download title.basics.tsv.gz and title.ratings.tsv.gz into /tmp first.')
    ratings, mean_rating = read_ratings()
    movies = read_movies(ratings, mean_rating)
    write_js(movies)
    print(f'Wrote {len(movies)} movies to {OUTPUT_PATH}')


if __name__ == '__main__':
    main()
