#!/usr/bin/env python3
import argparse
import json
import os
import re
import sys
import time
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
MOVIES_PATH = ROOT / 'src/data/movies.js'
TMDB_FIND_URL = 'https://api.themoviedb.org/3/find/{imdb_id}'


def load_movies(path):
    text = path.read_text(encoding='utf-8')
    match = re.search(r'export const MOVIES = (\[.*?\]);', text, re.S)
    if not match:
        raise SystemExit(f'Could not find MOVIES export in {path}')
    return json.loads(match.group(1))


def write_movies(path, movies):
    lines = [
        '// Generated by scripts/build_imdb_movies.py from IMDb non-commercial datasets.',
        '// Real descriptions can be added by scripts/enrich_movie_descriptions_tmdb.py using TMDb API overviews.',
        '// Sources: https://developer.imdb.com/non-commercial-datasets/ and https://developer.themoviedb.org/reference/find-by-id',
        'export const MOVIES = ' + json.dumps(movies, ensure_ascii=False, indent=4) + ';',
        '',
        'export const MOVIE_TITLES = MOVIES.map(movie => movie.title);',
        'export const MOVIE_DESCRIPTIONS = MOVIES.map(movie => movie.description);',
        '',
    ]
    path.write_text('\n'.join(lines), encoding='utf-8')


def request_json(url, token):
    request = Request(url, headers={
        'Authorization': f'Bearer {token}',
        'Accept': 'application/json',
        'User-Agent': 'web-faker-extension-data-builder/1.0',
    })
    with urlopen(request, timeout=20) as response:
        return json.loads(response.read().decode('utf-8'))


def fetch_tmdb_overview(imdb_id, token, language):
    query = urlencode({'external_source': 'imdb_id', 'language': language})
    url = f'{TMDB_FIND_URL.format(imdb_id=imdb_id)}?{query}'
    data = request_json(url, token)
    results = data.get('movie_results') or []
    if not results:
        return None
    overview = (results[0].get('overview') or '').strip()
    return overview or None


def enrich(movies, token, language, sleep_seconds, limit):
    updated = 0
    checked = 0
    for movie in movies:
        if limit is not None and checked >= limit:
            break
        checked += 1
        try:
            overview = fetch_tmdb_overview(movie['id'], token, language)
        except HTTPError as exc:
            if exc.code == 429:
                retry_after = int(exc.headers.get('Retry-After', '2'))
                time.sleep(retry_after)
                overview = fetch_tmdb_overview(movie['id'], token, language)
            else:
                print(f'{movie["id"]} {movie["title"]}: HTTP {exc.code}', file=sys.stderr)
                continue
        except (URLError, TimeoutError) as exc:
            print(f'{movie["id"]} {movie["title"]}: {exc}', file=sys.stderr)
            continue

        if overview:
            movie['description'] = overview
            movie['descriptionSource'] = 'tmdb'
            updated += 1
            print(f'updated {movie["id"]}: {movie["title"]}')
        else:
            print(f'no overview {movie["id"]}: {movie["title"]}')
        if sleep_seconds > 0:
            time.sleep(sleep_seconds)
    return updated, checked


def main():
    parser = argparse.ArgumentParser(description='Enrich generated IMDb movie records with real TMDb overviews.')
    parser.add_argument('--language', default='en-US', help='TMDb language, e.g. en-US, uk-UA, ru-RU')
    parser.add_argument('--sleep', type=float, default=0.05, help='Delay between requests in seconds')
    parser.add_argument('--limit', type=int, default=None, help='Only process first N movies')
    parser.add_argument('--dry-run', action='store_true', help='Fetch and report without writing movies.js')
    args = parser.parse_args()

    token = os.environ.get('TMDB_API_KEY') or os.environ.get('TMDB_READ_ACCESS_TOKEN')
    if not token:
        raise SystemExit('Set TMDB_API_KEY to a TMDb v4 read access token before running this script.')

    movies = load_movies(MOVIES_PATH)
    updated, checked = enrich(movies, token, args.language, args.sleep, args.limit)
    if not args.dry_run:
        write_movies(MOVIES_PATH, movies)
    print(f'Checked {checked}, updated {updated}.')


if __name__ == '__main__':
    main()
